### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by bubi24** [bubi24/outlay#1]
Implement Travis CI for the project

**Comment by gytimi** [comment]
The Travis build worked well.

**Comment by vidam94** [comment]
I reviewed it, it works. 👍

**Comment by micskeiz** [comment]
Are you sure Travis is building the full application? The build output is quite short, and gradle is not called at all. Check this please and compare it with the output of a local build.

**Comment by vidam94** [comment]
Now it really seems to be working :) :+1:
